#include<iostream>
using namespace std;
main () {
int n1;
int n2;
int n3;
int n4;
int n5;
int n6;
int n7;
int n8;
int n9;
int n10;
int n11;
int n12;
int n13;
int n14;
int n15;
int add;
int multiply;
int subtract;
int total;
cout << "Enter 1st number...";
cin >> n1 ;
cout << "Enter 2nd number...";
cin >> n2 ;
cout << "Enter 3rd number...";
cin >> n3 ;
cout << "Enter 4th numbrer...";
cin >> n4 ;
cout << "Enter 5th numbrer...";
cin >> n5 ;
cout << "Enter 6th numbrer...";
cin >> n6 ;
cout << "Enter 7th numbrer...";
cin >> n7 ;
cout << "Enter 8th numbrer...";
cin >> n8 ;
cout << "Enter 9th numbrer...";
cin >> n9 ;
cout << "Enter 10th numbrer...";
cin >> n10 ;
cout << "Enter 11th numbrer...";
cin >> n11 ;
cout << "Enter 12th numbrer...";
cin >> n12 ;
cout << "Enter 13th numbrer...";
cin >> n13 ;
cout << "Enter 14th numbrer...";
cin >> n14 ;
cout << "Enter 15th numbrer...";
cin >> n15;
add = n1+n2+n3+n4+n5;
multiply = n6*n7*n8*n9*n10;
subtract = n11-n12-n13-n14-n15;
total = (add + multiply)-subtract;
cout << "Total..." << total ;
}